"use client";

export default function ClientProjectView() {
  return (
    <div id="project-wrapper">
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
      <h1>Client Project</h1>
    </div>
  );
}
