import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/client-view/common-layout";
import ScrollToTopButton from "@/components/ScrollToTopButton/ScrollToTopButton";
import GlobalState from "@/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amit's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <CommonLayout>{children}</CommonLayout>
          <ScrollToTopButton></ScrollToTopButton>
        </GlobalState>
      </body>
    </html>
  );
}
